### PR TITLE
Avoid drops on content

### PR DESCRIPTION
**Pull request by rrees**
I'm trying to avoid this plugin clobbering content during the drop (#11).

To do this I've turned the test suite into a unit test (I couldn't get the tests working in a browser context) and exposed more of the helper functions to help determine whether the drop is valid.

### CODE REVIEW

**Comment by cutandpastey** [comment]
As noted here: https://github.com/guardian/scribe-plugin-drag-and-drop/issues/13 tests wont work until you add babel support which can be done by changing `node` to `node_modules/.bin/babel-node`  here https://github.com/guardian/scribe-plugin-drag-and-drop/blob/master/run-tests.sh#L11 assuming you have babel installed. Doing that should clean this up a bit.

**Comment by rrees** [comment]
@cutandpastey re: ES6 in that case I think we should parameterise the run-tests.sh to accept an ENV variable for the node runner.

**Comment by rrees** [comment]
Updated the PR with the babel-node runner (invoked in `package.json`, defaulting to node)

**Comment by cutandpastey** [comment]
This renders `./run-tests.sh` unusable? Im not really a fan of this.

**Comment by rrees** [comment]
@cutandpastey No, it doesn't make it unusable but by default it won't compile something that node doesn't understand, I can make babel-node the default but is that the case that this will only work with babel-node?

**Comment by cutandpastey** [comment]
If you would like to use any es6 then yes. The problem is that when you are using the driver (testing behaviour) you are acting on the compiled source within the browser. When you "require" a module in for a unit test it is within the node context so needs to be compiled. As far as I can work out `babel/register` hijacks the `require` function uses `fs.readFileSync` to get the raw text, compiles it and returns it to node.

**Comment by rrees** [comment]
Can we review the fix element to see if it sorts the drop overwriting the content?

**Comment by hmgibson23** [comment]
I think the `isEmpty` stuff is okay for now. Definitely keen to do some testing though! Will close this and make an issue.

**Pull request closed without merging**
